version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"  
    depends_on:     
      - db
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
  
  redis:
    image: redis:5-alpine
    command: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - 'redis:/data'
 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5

  golang-app:
    build: ./golang-service
    restart: always
    # command: bash -c "sh wait-for-it.sh rabbitmq:15672"
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - .:/golang-app
    ports:
      - "8080:8080"   

volumes:
  mysql-data:
  gem_cache:
  redis: